### ISSUE TITLE
Use TRegisteredComponent.OnCreate to create initial TCastlePolygon2D / TCastleLine2D contents at design-time

### ISSUE THREAD

**Issue by michaliskambi** [KumurTash/CastleLines2D#2]
I noticed you use a pattern like this to fill a newly-created instance of TCastlePolygon2D / TCastleLine2D with initial points:

```delphi
constructor TCastlePolygon2D.Create(AOwner: TComponent);
begin
  inherited;
  ...

  {$ifdef CASTLE_DESIGN_MODE}
  Points.Add(Vector2(0,80));
  Points.Add(Vector2(25,35));
  ....
  ReLoad;
  {$endif}
end;
```

It means that this initialization happens always (at design-time, in editor) when `TCastlePolygon2D` is created, even when `TCastlePolygon2D` is created only to be deserialized (loaded) from a JSON file. In your code, these `Points` will be effectively overridden later by `TCastleLine2DBase.CustomSerialization`, which makes the end result correct... but adding these points at every construction is unnecessary.

It may be better to just add these initial points *once* when the TCastlePolygon2D / TCastleLine2D are added by user to the design. This is the purpose of `TRegisteredComponent.OnCreate` method. See https://castle-engine.io/custom_components#_children_components_that_user_can_freely_edit_and_remove_using_tregisteredcomponent_oncreate for usage, although the example there is more complicated than you need, as the example shows how to add children components. You instead want to just initialize points. Something like this may be good:

```delphi
type
  TCastlePolygon2D = class...
  private
    class procedure CreateInitialPoints(Sender: TObject);
    ...
  end;

class procedure TCastlePolygon2D.CreateInitialPoints(Sender: TObject);
begin
  P := Sender as TCastlePolygon2D;
  P.Points.Add(Vector2(0,80));
  P.Points.Add(Vector2(25,35));
  ....
  P.ReLoad;
end;

var
  R: TRegisteredComponent;
initialization
  R := TRegisteredComponent.Create;
  R.ComponentClass := TCastlePolygon2D;
  R.Caption := ['Polygon2D Transform'];
  R.OnCreate := {$ifdef FPC}@{$endif}TMyRectanglesGroup.CreateInitialPoints;
  RegisterSerializableComponent(R);
end.
```

**Comment by KumurTash** [comment]
Thanks for reporting!
I fixed it.
